# fly.toml app configuration file generated for portofolio-alexandru on 2024-06-21T17:52:14+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portofolio-alexandru'
primary_region = 'otp'

[[statics]]
  guest_path = "/app/src/assets"
  url_prefix = "/src/assets"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
